### ISSUE TITLE
[Adblock BUG] On the latest version of spotify, adblock no longer works.

### ISSUE THREAD

**Issue by lunarrvxx** [CharlieS1103/spicetify-extensions#104]
## Describe bug
Exactly as the title says, all audio, banner, and popup visual ads once again function and require a premium spotify membership to alleviate. 
## Steps to replicate
Use Adblock on the latest version of spotify and spicetify.
## Necessary screenshots
![image](https://github.com/CharlieS1103/spicetify-extensions/assets/149847075/15ad915a-00e6-41b3-ae57-fca005e13a47)

## Spicetify and Spotify Version
Latest version for each.

## Config file:
I couldn't find it (I've never looked through the config files of something in spicetify before), but it's the unedited default one.

**Comment by Xarl** [comment]
Have the same Problem and so do all that use that App
