### ISSUE TITLE
Ads when connecting to a speaker

### ISSUE THREAD

**Issue by Ehxn** [CharlieS1103/spicetify-extensions#107]
## Describe bug
whenever I connect to a speaker, audio ads still play
## Steps to replicate
just play a playlist and see ads still appear
## Necessary screenshots
![image](https://github.com/CharlieS1103/spicetify-extensions/assets/149090619/5c80b799-e536-44cb-9a7d-65063ab90e95)
## Spicetify and Spotify Version
![image](https://github.com/CharlieS1103/spicetify-extensions/assets/149090619/ea703924-dd4e-46f4-b803-eaccf414b488)

**Comment by CharlieS1103** [comment]
i mean i'd assume the only way this happens is if said speaker is making the requests to spotify itself, and given you're using an echo, that's probably the case
