### ISSUE TITLE
Upgrade button not removed in Adblock extension

### ISSUE THREAD

**Issue by itsmeboy0** [CharlieS1103/spicetify-extensions#11]
**Describe the solution you'd like**
Add an option to remove the upgrade button that appears on the top of spotify

**Additional context**
![image](https://user-images.githubusercontent.com/75471378/157395272-3b1c1c9e-676d-45e8-b589-cdf6b13bd60c.png)

**Comment by CharlieS1103** [comment]
Should already work, send your full config/xpui file please

**Comment by itsmeboy0** [comment]
```ini
[Setting]
inject_css              = 1
overwrite_assets        = 1
check_spicetify_upgrade = 0
replace_colors          = 1
spotify_launch_flags    = 
spotify_path            = C:\Users\itsmeboy\AppData\Roaming\Spotify
prefs_path              = C:\Users\itsmeboy\AppData\Roaming\Spotify\prefs
current_theme           = 
color_scheme            = 

[Preprocesses]
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1

[AdditionalOptions]
home_config           = 1
experimental_features = 1
extensions            = adblock.js
custom_apps           = spicetify-marketplace|lyrics-plus|new-releases
sidebar_config        = 1

[Patch]

; DO NOT CHANGE!
[Backup]
version = 1.1.80.699.gc3dac750
with    = 2.9.2
```

Installing it from the marketplace does not work as well.

**Comment by itsmeboy0** [comment]
Using it with [SpotifyNoPremium](https://github.com/Daksh777/SpotifyNoPremium/) works.

**Comment by itsmeboy0** [comment]
I've found a fork that removes the upgrade button: https://github.com/DarkVanityOfLight/SpicetifyAdBlock/blob/main/adblock.js

Ping @DarkVanityOfLight
