### ISSUE TITLE
[Adblock BUG] Popups ads do not get blocked some times

### ISSUE THREAD

**Issue by Daksh777** [CharlieS1103/spicetify-extensions#12]
## Describe bug
The banner/popups ad does not get blocked and stays for a few minutes before being blocked by the extension again

## Steps to replicate
Happens randomly

## Necessary screenshots
![image](https://user-images.githubusercontent.com/43648146/159110217-c2f05ed0-752a-4017-99e5-9b1d0d1b4c4f.png)

## Spicetify and Spotify Version
Spotify for Windows 1.1.81.604.gccacfc8c
Spicetify v2.9.2

**Comment by Scherso** [comment]
Same has happened to me, I came here to see if someone else had already made an issue on it.

Screenshot: 
<img width="900" alt="image" src="https://user-images.githubusercontent.com/90007553/159129608-b7a9b583-003c-4848-ac22-a08b95d76244.png">

**Comment by Daksh777** [comment]
Seems like that is the homepage ad, you can use my theme which will block it using CSS: https://github.com/Daksh777/SpotifyNoPremium
But the popup ads still come a few times for some reason.

**Comment by Scherso** [comment]
Smoothest plug I have seen

**Comment by CharlieS1103** [comment]
I mean this is just the new update,
Will patch it in a quick sec once i'm done with vacation. @Scherso

**Comment by Scherso** [comment]
It works after playing with my backup, running `spicetify backup` then making sure the css mappings load somehow fixed it once I re-ran `spicetify backup apply`. Still weird that it just stops working sometimes though.

**Comment by CharlieS1103** [comment]
@Scherso Alright, i'll check it out in depth after I get back

**Comment by Scherso** [comment]
Oh yeah, this has not been an issue for me recently, You have the go-ahead from me to close this.

**Comment by CharlieS1103** [comment]
> Oh yeah, this has not been an issue for me recently, You have the go-ahead from me to close this. 

Appreciate it

**Comment by Daksh777** [comment]
Yes @CharlieS1103, works well!
Thank you :D
