### ISSUE TITLE
[Adblock BUG] Song repeats/loops a bit when audio ad is blocked

### ISSUE THREAD

**Issue by Daksh777** [CharlieS1103/spicetify-extensions#13]
## Describe bug
Sometimes, when an audio ad is being blocked and the song has already started playing, a small part of the song gets repeated/looped.

## Spicetify and Spotify Version
Spotify for Windows 1.1.81.604.gccacfc8c
Spicetify v2.9.2

**Comment by CharlieS1103** [comment]
@Daksh777 Most likely unrelated to adblock, either a spotify issue or another extension

**Comment by Daksh777** [comment]
No other extension is installed except adblock, this only happens when I use adblock extension.
Reinstalling Spotify didn't help either.

**Comment by Daksh777** [comment]
Updated to v1.1.81 and this problem did occur on the stock Spotify app as well.
Seems like it's a bug on the actual Spotify client, really sorry for creating this issue: https://community.spotify.com/t5/Desktop-Windows/Starting-a-song-short-loop-in-the-beginning-windows-desktop/m-p/5356090#M107418
