### ISSUE TITLE
[Adblock BUG] Video and audio ads are back

### ISSUE THREAD

**Issue by Daksh777** [CharlieS1103/spicetify-extensions#16]
![image](https://user-images.githubusercontent.com/43648146/185655229-1fc60fca-c4bf-4ebe-896f-c2b9ae0f937f.png)

## Spicetify and Spotify Version
Spicetify v2.11.1
Spotify 1.1.92.647.ga4397eb7

**Comment by CharlieS1103** [comment]
@Daksh777 I had someone ask me about this and it seemed they used your install script, once they installed manually from my repo it started working. Going to close this issue because of that.

**Comment by CharlieS1103** [comment]
Nvm, the platform hook is broken on latest release.

**Comment by Daksh777** [comment]
Oh woops, seems like a Spicetify problem then? So sorry for opening it here.

**Comment by CharlieS1103** [comment]
@Daksh777 All good, problem should be resolved once someone who isn't as lazy as me decides to make a new spicetify release.

**Comment by Daksh777** [comment]
Hahaha, and the new release is here already!
