### ISSUE TITLE
[FixEnhance Bug] Describe bug here.

### ISSUE THREAD

**Issue by foco76** [CharlieS1103/spicetify-extensions#17]
## Describe bug
Can't find Toggle in the Profile menu.

## Steps to replicate
installing fixEnhance.js as instucted
opening spotify 
go to profile menu
***error-No toggle menu button**

## Necessary screenshots
![Screenshot (63)](https://user-images.githubusercontent.com/109255482/190830806-2dbc5b51-e076-4e6a-8e0d-25ccaeb7f41b.png)

## Spicetify and Spotify Version
Spicetify  - 2.13.1
Spotify - 1.1.94.870.gf994cb0b(Windows)

## Config file:
`[Setting]
overwrite_assets        = 1
check_spicetify_upgrade = 0
prefs_path              = C:\Users\Vihanga 2Hi5\AppData\Roaming\Spotify\prefs
current_theme           = marketplace
color_scheme            = 
inject_css              = 1
replace_colors          = 1
spotify_launch_flags    = 
spotify_path            = C:\Users\Vihanga 2Hi5\AppData\Roaming\Spotify

[Preprocesses]
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1

[AdditionalOptions]
extensions            = autoSkipVideo.js|bookmark.js|keyboardShortcut.js|loopyLoop.js|popupLyrics.js|shuffle+.js|trashbin.js|fixEnhance.js
custom_apps           = marketplace|lyrics-plus|reddit|new-releases
sidebar_config        = 1
home_config           = 1
experimental_features = 1

[Patch]

; DO NOT CHANGE!
[Backup]
version = 1.1.94.870.gf994cb0b
with    = 2.13.1

`

**Comment by CharlieS1103** [comment]
This extension has no purpose on newer versions of Spotify
