### ISSUE TITLE
[Adblock BUG] Describe bug.

### ISSUE THREAD

**Issue by Ugniuakuiba123** [CharlieS1103/spicetify-extensions#23]
## Necessary screenshots 
![image](https://user-images.githubusercontent.com/116912166/198704288-11e03e19-c0fb-4531-bbad-591c67332e47.png)

**Comment by CharlieS1103** [comment]
make a new issue and include the relevant information.

**Comment by Ugniuakuiba123** [comment]
how do i get the info
bruh how did u help me
rude

**Comment by Ugniuakuiba123** [comment]
what even is a config file im stoopid
