### ISSUE TITLE
I found ad in podcast

### ISSUE THREAD

**Issue by DawaDokuna** [CharlieS1103/spicetify-extensions#25]
**Describe the bug**

**To Reproduce**
1. Go to podcast
2. Click on play

**Expected behavior**
I found ad in podcast

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**

**Comment by CharlieS1103** [comment]
yeah podcasts don't do ads the same way songs do.

**Comment by citizenserious** [comment]
Is there a way we can mute these ads as an alternative solution? Like these app does it on android for example https://github.com/aghontpi/ad-silence.

Thank you for looking into it (:
