### ISSUE TITLE
[Adblock BUG] Extension adblock.js not found

### ISSUE THREAD

**Issue by The-Unknown-Programming-Student** [CharlieS1103/spicetify-extensions#26]
While running the commnd in windows powershell x86 the extension for adblock.js was not found wherein i copied and pasted the files as said in the marketplace.
![image](https://user-images.githubusercontent.com/116381063/201313333-a20f78bd-e31a-4abb-bc9f-0437daad9b82.png)
can you pls help me with it.

Spotify version: 1.1.98
Spicetify Version: 2.14.1

**Comment by CharlieS1103** [comment]
You don't have the file installed.

**Comment by The-Unknown-Programming-Student** [comment]
I had the file installed and i did a mistake. Instead of pastting only the .js file i had pasted the whole zipped file😅

Now it works
