### ISSUE TITLE
[Phrase2Playlist BUG] It just, doesn't work for some text?

### ISSUE THREAD

**Issue by msr8** [CharlieS1103/spicetify-extensions#27]
## Describe bug
it for some reasons just doesn't produce a playlist for certain phrases

<br>

## Steps to replicate
Tell the program to convert the phrase "What the fuck did you just fucking say to me you little bitch I will have you know I graduated top of my class in the Navy Seals and Ive been involved in numerous secret raids on top secret terror organisations and I have over 300 confirmed kills I am trained in gorilla warfare and Im the top sniper in the entire US armed forces" to a playlist

<br>

## Necessary screenshots
Prompt:
![Screenshot 2022-11-21 at 7 52 37 PM](https://user-images.githubusercontent.com/79649185/203078550-79ed1d73-bae3-477b-9437-583aee6c00b0.png)

Output (an empty playlist):
![Screenshot 2022-11-21 at 7 52 15 PM](https://user-images.githubusercontent.com/79649185/203078470-11a6179f-80d2-4ff7-9ca3-f05d395c99e8.png)

## Spicetify and Spotify Version
Spicetify version: 2.14.1
Spotify version: Spotify for macOS (Intel) 1.1.98.691.gf759311c

<br>

## Config file:
where is that located?

**Comment by CharlieS1103** [comment]
lmfao, seems for whatever reason the word "i" doesn't work and returns an undefined track. One second
