### ISSUE TITLE
[Feature Request] Show Album Art in Full View Extension

### ISSUE THREAD

**Issue by karimawii** [CharlieS1103/spicetify-extensions#28]
Hey, I have an extension idea in mind, I think it's very good, I feel like I need it all the time

Album arts are getting quite the production value nowadays, sometimes they look so good, but I can't see all the details even when I expand it, so my suggestion is to add a context menu option when right-clicking the album art:

![image](https://user-images.githubusercontent.com/69881381/204167476-eed7caac-41b1-4996-9ad8-130ea4750e8b.png)

and add a sub-context menu or whatchamacallit that has options like:
- Download Full Size Album Art
- View Full Size Album Art (if possible (easy to implement) in client, if not maybe open in browser)
- Copy Album Art image URL

**Comment by karimawii** [comment]
There's an extension for that now by [Raghavan](https://github.com/Tetrax-10/):
https://github.com/Tetrax-10/Spicetify-Extensions/tree/master/Image-Opener

**Comment by karimawii** [comment]
Thank you Charlie!

![7noq4x](https://github.com/CharlieS1103/spicetify-extensions/assets/69881381/3eda09ca-47ca-429d-8c7b-d15951797c40)


>I'm just kidding btw, I love Charlie

**Comment by Tetrax-10** [comment]
Ohh never knew that idea existed before lol.

> ![7noq4x](https://user-images.githubusercontent.com/69881381/242112714-3eda09ca-47ca-429d-8c7b-d15951797c40.gif)

Good one 😂

**Comment by CharlieS1103** [comment]
> Thank you @CharlieS1103
> 
> ![7noq4x](https://user-images.githubusercontent.com/69881381/242112714-3eda09ca-47ca-429d-8c7b-d15951797c40.gif)
> 
> > I'm just kidding btw, I love Charlie

I got you covered bro.
