### ISSUE TITLE
[Adblock BUG] Adblock isn't working

### ISSUE THREAD

**Issue by lis0** [CharlieS1103/spicetify-extensions#29]
## Describe bug
I'm getting ads

## Steps to replicate
Get adblock

## Necessary screenshots
I will add a screenshot as soon as I get any AD

## Spicetify and Spotify Version
Spotify na Windows
1.1.99.878.g1e4ccc6e
Spicetify v2.14.1

## Config file:
Which?

**Comment by CharlieS1103** [comment]
Update spicetify
