### ISSUE TITLE
[Adblock BUG] Describe bug.

### ISSUE THREAD

**Issue by creightonmcc** [CharlieS1103/spicetify-extensions#30]
## Describe bug 
It's playing ads
## Steps to replicate
Wait for it to play or show a UI add.
## Necessary screenshots
https://user-images.githubusercontent.com/119522131/206315734-84056db8-654a-4221-8acb-dc371139102e.png

## Spicetify and Spotify Version
Spicetify Version: 2.14.3
Spotify Version: Doesn't show in "About Spotify"

**Comment by CharlieS1103** [comment]
If your Spotify version isn't showing in about Spotify then you have something very wrong with your install lol, recommend reinstalling Spotify and spicetify
