### ISSUE TITLE
[Adblock BUG] Doesn't keep audio ads from playing anymore

### ISSUE THREAD

**Issue by stephan-steinmiller** [CharlieS1103/spicetify-extensions#42]
## Describe bug
Doesn't keep audio ads from playing anymore

## Steps to replicate
Start spotify with spicetify and the adblock extention installed and wait for audio advertisementss to come up, whilst litening to music.

## Necessary screenshots
![image](https://user-images.githubusercontent.com/37940248/232308697-41b65f31-e667-4dcf-aa31-49826c34b708.png)

## Spicetify and Spotify Version
Spicetify Version 2.17.0 and Spotify Version 1.2.9.743.g85d959Sd

## Config file:
[config-xpui.zip](https://github.com/CharlieS1103/spicetify-extensions/files/11242181/config-xpui.zip)

**Comment by CharlieS1103** [comment]
upgrade spicetify.
