### ISSUE TITLE
[Adblock BUG] Describe bug.

### ISSUE THREAD

**Issue by gojusataru** [CharlieS1103/spicetify-extensions#46]
#there is ads while i added the ad blocker # Describe bug

## Steps to replicate

#
![image](https://github.com/CharlieS1103/spicetify-extensions/assets/107445100/cacb66ec-7c0b-4531-b751-4d028be5d603)
![image](https://github.com/CharlieS1103/spicetify-extensions/assets/107445100/5c17432f-1bd6-4b8f-870a-15ddf32c79d0)
# Necessary screenshots

#the last verisoins# Spicetify and Spotify Version

#i don,t know what is that# Config file:

**Comment by CharlieS1103** [comment]
Are you Egyptian by any chance?

**Comment by gojusataru** [comment]
Yes I’am Egyptian . why ? Sent from Mail for Windows From: CharlieSent: ‏12 ‏يونيو,‏ ‏2023 ‏07:19 ‏مTo: CharlieS1103/spicetify-extensionsCc: gojusataru; AuthorSubject: Re: [CharlieS1103/spicetify-extensions] [Adblock BUG] Describe bug. (Issue #46) Are you Egyptian by any chance?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by CharlieS1103** [comment]
Marketplace doesn't work in egypt, manually install extensions
