### ISSUE TITLE
[Adblock BUG] Describe bug.

### ISSUE THREAD

**Issue by belalabdo1234** [CharlieS1103/spicetify-extensions#57]
## Describe bug
its blocking visual adds but since the last update it stopped blocking audio adds 
## Steps to replicate
just listen to music while enabling the add blocker 
## Spicetify and Spotify Version
latest

**Comment by thefakequake** [comment]
I also have this problem

**Comment by Vyxxxx** [comment]
Me too.

**Comment by thefakequake** [comment]
nope, UK

**Comment by Pokrzywnik** [comment]
I also have problems. I was using old version of spotify/spicetify.
Things i tried:
-updated spicetify (still had ads)
-updated spotify and reapply spicetify (still had ads)
-uninstalled adblock extension, downloaded and installed it manually - ads still there

not from egypt, Poland here. Last time i listened (17.06.2023) it was working fine. Do you need any logs?

**Comment by DeveloLongScript** [comment]
bro same here

**Comment by DeveloLongScript** [comment]
i found a work around. all you have to do is run
```js
Spicetify.Platform.AdManagers.audio.disable();
```
in the spotify console ( open by using `Ctrl+Shift+I` )

It only works until spotify closes (so everytime you have to use that hack)

**Comment by DeveloLongScript** [comment]
alright. i found a workaround. download [noWatchTime.zip](https://github.com/CharlieS1103/spicetify-extensions/files/11807369/noWatchTime.zip), decompress and move noWatchTime into the extensions folder.

extension folder:
> | **Platform**   | **Path**                                                                             |
> |----------------|--------------------------------------------------------------------------------------|
> | **Linux**      | `~/.config/spicetify/Extensions` or `$XDG_CONFIG_HOME/.config/spicetify/Extensions/` |
> | **MacOS**      | `~/spicetify_data/Extensions` or `$SPICETIFY_CONFIG/Extensions`                      |
> | **Windows**    | `%appdata%\spicetify\Extensions\`                                                   |
then, use `spicetify apply`. this works **every** time you open the folder. enjoy!

step-by-step guide: https://gist.github.com/DeveloLongScript/7741173730c6ac3c84bf0799a465c59c

**Comment by CharlieS1103** [comment]
Going to roll out a patch right now

**Comment by xagzu** [comment]
Is the patch out yet? The adblocker still doesn't work.

**Comment by CharlieS1103** [comment]
Could I ask what version of spicetify/Spotify you're all on

**Comment by Noxde** [comment]
> Could I ask what version of spicetify/Spotify you're all on

Im on 2.16.2

**Comment by ninjadev64** [comment]
It's not blocking any ads for me, I'm on Spicetify 2.17.0

**Comment by CharlieS1103** [comment]
Should be fixed now, wait up to  of 24 hours to see the changes

**Comment by peege-on** [comment]
> Should be fixed now, wait up to of 24 hours to see the changes

still playing audio ads on 2.20.1 :(

**Comment by tjch-o** [comment]
same it still plays audio ads on 2.20.2 for me

**Comment by peege-on** [comment]
> @peege-on @tjch-o Are either of you from egypt

not me

**Comment by CharlieS1103** [comment]
@peege-on @tjch-o What version of spotify are you guys on?

**Comment by peege-on** [comment]
> @peege-on @tjch-o What version of spotify are you guys on?

Spotify for Windows
1.2.13.661.ga588f749
Spicetify v2.20.2

**Comment by belalabdo1234** [comment]
I'm from Egypt yes

**Comment by tjch-o** [comment]
Spotify for Windows
1.2.14.1149.ga3ae422d
Spicetify v2.20.2

**Comment by DeveloLongScript** [comment]
If you guys are still having ads then use the patch i made above ^^^^^^

**Comment by CharlieS1103** [comment]
> If you guys are still having ads then use the patch i made above ^^^^^^

I rolled out a patch which should resolve the issue mentioned.

**Comment by omelkonian** [comment]
I'm afraid I am still hearing ads:
- Spicetify v2.22.0
- Marketplace v0.8.7

**Comment by xagzu** [comment]
I am hearing advertisments aswell.

**Comment by EdentheDumbie** [comment]
i also have this issue (im from israel if that helps) and im on the newest version of everything
