### ISSUE TITLE
[Adblock BUG] Still have ads

### ISSUE THREAD

**Issue by GeneralChauhan** [CharlieS1103/spicetify-extensions#60]
## Describe bug
I still have the ads
## Steps to replicate
Just installed Spicetify and the extensions

**Comment by CharlieS1103** [comment]
Until someone who knows how to debug has this issue I really can't help you out man

**Comment by Adamkadaban** [comment]
Can confirm that this is recently an issue. I'll try locating the issue in a bit

**Comment by CharlieS1103** [comment]
@Adamkadaban Would appreciate that very much sir

**Comment by Adamkadaban** [comment]
Haven't been able to find the source of the issue, but it seems (for me at least) that spicetify isn't loading extensions properly.

Run `spicetify -e update` to check if extensions have been installed properly. If there are any issues, just download the script manually from this repo and put it in the `Extensions` directory

**Comment by CharlieS1103** [comment]
oh are you egyptian? @Adamkadaban

**Comment by CharlieS1103** [comment]
If I could also get a list of the isps people who have this bug are using it might be helpful

**Comment by mcoulmeau** [comment]
Same bug here, but i'm in France my ISP is Free

**Comment by mcoulmeau** [comment]
> Run `spicetify -e update` to check if extensions have been installed properly. If there are any issues, just download the script manually from this repo and put it in the `Extensions` directory

Indeed it seems the extension doesn't install properly using the spicetify-marketplace. Manually install the script seems to work for me

**Comment by CharlieS1103** [comment]
Closing this as none of the issues seem related to Adblock.
