### ISSUE TITLE
[Adblock BUG] Please remove this extension

### ISSUE THREAD

**Issue by symbion6** [CharlieS1103/spicetify-extensions#61]
## Describe bug
I love Spicetify and it's great that Spotify hasn't banned it in any way, so far.
But if you add an extension to block ads, it's going in the wrong direction.
If there's a big reason for them to block Spicetify, it's because of this.

Please remove this feature, please respect Spotify's business model and please don't put other Spicetify users in danger by keeping this extension online, thank you.

**Comment by DeveloLongScript** [comment]
#

**Comment by DawarTheDastardly** [comment]
counterpoint: piracy is based and im not paying for premium
