### ISSUE TITLE
Adblocker stopped working

### ISSUE THREAD

**Issue by Nebzla** [CharlieS1103/spicetify-extensions#64]
## Describe bug
The ad blocker has suddenly stopped working. I've tried reinstalling the extension already with no success

## Steps to replicate
Using latest version of Spotify and spicetify, I launch spotify and ads are still present

## Spicetify and Spotify Version
Spicetify: v2.20.0
Spotify: Latest

**Comment by Nebzla** [comment]
What do you mean not planned? The extension is not functioning correctly, i'm not asking for a new feature or anything so im not sure why you closed it saying nothing

**Comment by CharlieS1103** [comment]
Sorry about that, there's already a lot of issues with the same problem so this one isn't really necessary. You can find the others in the issues tab.

**Comment by Nebzla** [comment]
Ah I see I was just a bit confused when you closed it because I thought you misunderstood

**Comment by CharlieS1103** [comment]
Yup sorry about that, should have left a comment but was out with friends at the time.
