### ISSUE TITLE
[Adblock BUG] Describe bug.

### ISSUE THREAD

**Issue by WhereTheCash** [CharlieS1103/spicetify-extensions#70]
Does not block any ads anymore

**Comment by okaywait0817** [comment]
Doesnt block visual or audio ads, both spotify and spicetify are up to date

Reinstalled spicetify, didnt work
Reinstalled spotify and spicetify, still didnt work :/

**Comment by okaywait0817** [comment]
i figured out its an issue with spicetify not loading them properly, just had to manually reinstall it
