### ISSUE TITLE
[Phrase2Playlist BUG] Weird behaviour with short words

### ISSUE THREAD

**Issue by MalTeeez** [CharlieS1103/spicetify-extensions#73]
## Describe bug
When inputting short words I get normal playlists for some, but for certain other words I either get an empty playlist or sometimes a wrong replacement which only partially consists of my word.

Note: I saw #27 and tried "i", which worked, but weirdly "I" doesn't work.
## Steps to replicate

Empty playlist:
Create a Phrase2Playlist with "I have a Dream"

Wrong song replacement:
Create a Phrase2Playlist with "Trees and Tr" - replaces "Tr" with "Traum"

## Spicetify and Spotify Version
Spotify for Windows (64 Bit)
1.2.17.834.g26ee1129
Spicetify v2.22.2

**Comment by CharlieS1103** [comment]
yeeahhhh, so for short words spotify search so you have to manually input them, if you want to make a PR for a few the code should be pretty straight forward

**Comment by MalTeeez** [comment]
Added words in #74, but I still have no idea how "Tr" became "Traum", any ideas?

**Comment by MalTeeez** [comment]
Well that would explain it, do you think it would make sense to check if a song matches its word if its 2 letters long or to just ignore 2 letter words?

**Comment by MalTeeez** [comment]
Fixed with #79.
