### ISSUE TITLE
Blank ads banner

### ISSUE THREAD

**Issue by aaxiidd** [CharlieS1103/spicetify-extensions#78]
after opening spotify or in a while after playing music, theres showing blank ads banner (dark transparent overlay on screen but no ads shown) sometimes can exit by pressin esc button, and sometimes i should relaunch spotify to fix that

**Comment by ca-kraa** [comment]
its work thanks

**Comment by thaynos** [comment]
> Try disabling this ![image](https://user-images.githubusercontent.com/116754124/265446616-5590642d-f0a6-470f-af44-398ffe8d0a49.png)

is there any documentation for the experimental features? how do we know what each is supposed to do?

**Comment by Tequinzyy** [comment]
> > Try disabling this ![image](https://user-images.githubusercontent.com/116754124/265446616-5590642d-f0a6-470f-af44-398ffe8d0a49.png)
> 
> is there any documentation for the experimental features? how do we know what each is supposed to do?

one guy issued a support ticket in their discord server and I read that's all
