### ISSUE TITLE
[Adblock BUG] Describe bug.

### ISSUE THREAD

**Issue by HanifVW** [CharlieS1103/spicetify-extensions#84]
## Spotify for Windows (64 bit)
1.2.21.1104.g42cf0a50
Spicetify v2.23.2

**Comment by Slickbignick** [comment]
Also facing the same issue

**Comment by Duck-le-bleu** [comment]
Same issue started yesterday. I reinstalled the extension again, and that worked till today. Reinstalling does nothing, still having ads.

**Comment by SpektacleFR** [comment]
Same issue, MacOS with Spicetify 2.23.2.

**Comment by arcticyouge** [comment]
Same issue, windows with Spicetify 2.23.2.

**Comment by Neglevin** [comment]
also having this same issue, spicetify 2.23.2

**Comment by xCraimax** [comment]
same here!

**Comment by NightmareBoltFr** [comment]
Same issue on Windows with Spicetify v2.24.2

**Comment by c0upe12** [comment]
The "SpotifyNoPremium" Theme seems to work for a temporary fix.

**Comment by CharlieS1103** [comment]
Will fix tonight
