### ISSUE TITLE
Rate limiting when creating a feature based playlist

### ISSUE THREAD

**Issue by wtrfl** [CharlieS1103/spicetify-extensions#9]
Hello! When trying to use the feature-based playlist extension, I noticed that the playlist was never getting created. Looking in the console showed that when sending a get request to `https://api.spotify.com/v1/search...`, the request was returning with code 429. I believe this is because the playlist is getting one song over and over again.

**Comment by CharlieS1103** [comment]
@wtrfl The odds of that happening are very low, bit of an odd request here, but would you mind sending me the playlist you're using it on?

**Comment by wtrfl** [comment]
One playlist I tried it on was this (https://open.spotify.com/playlist/5t0EPzC0CpehEnbG2caS2P?si=f17b9f9578d34222) (37 songs) with this error returning from xpui.js
![image](https://user-images.githubusercontent.com/78034265/149223232-b8d7f136-a5c3-4467-8de8-772bc1081721.png)
I also cannot test the API out myself because I have no API key. I thought variation might help so I also tried on a long playlist (150+ songs) and a short playlist (2 songs).

**Comment by CharlieS1103** [comment]
I don't believe the issue is something with the extension as it works fine for me on the same playlist, it's most likely an issue with either country restrictions or something with your network.
