### ISSUE TITLE
[Adblock BUG] Describe bug.

### ISSUE THREAD

**Issue by bfoyewf** [CharlieS1103/spicetify-extensions#95]
## Describe bug
Banner ads are being blocked but pop-up audio ads are not :scream:

## Steps to replicate
Upgraded to latest spicetify (2.24.2) and ran `spicetify restore backup apply`

## Necessary screenshots
Installed ad blocker:
![image](https://github.com/CharlieS1103/spicetify-extensions/assets/146456415/f2738d37-87aa-466d-b8f9-4ecd8d57b6bf)

Add popping up after about 3 - 4 songs:
![image](https://github.com/CharlieS1103/spicetify-extensions/assets/146456415/a9533a41-f900-41eb-b20a-0d87828adb94)

## Spicetify and Spotify Version
![image](https://github.com/CharlieS1103/spicetify-extensions/assets/146456415/316bc2f9-e653-4b4f-b925-54f830d4d93a)
Spotify for Windows (64 bit)
1.2.21.1104.g42cf0a50
Spicetify v2.24.2

## Config file:
[Setting]
spotify_path            = C:\Users\user\AppData\Roaming\Spotify
prefs_path              = C:\Users\user\AppData\Roaming\Spotify\prefs
color_scheme            = 
check_spicetify_upgrade = 0
current_theme           = marketplace
inject_css              = 1
replace_colors          = 1
overwrite_assets        = 0
spotify_launch_flags    = 
inject_theme_js         = 1

[Preprocesses]
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1

[AdditionalOptions]
extensions            = 
custom_apps           = marketplace
sidebar_config        = 1
home_config           = 1
experimental_features = 1

[Patch]

; DO NOT CHANGE!
[Backup]
version = 1.2.21.1104.g42cf0a50
with    = 2.24.2

**Comment by Manuelxcv** [comment]
Use https://github.com/mrpond/BlockTheSpot#installationupdate

**Comment by HeyThatsMyToast** [comment]
> Use https://github.com/mrpond/BlockTheSpot#installationupdate

I've started using SpotX. You have a few more features compared to BlockTheSpot.
