### ISSUE TITLE
[Adblock BUG] it doesent block any of the audio add

### ISSUE THREAD

**Issue by sceriffoo** [CharlieS1103/spicetify-extensions#96]

**Comment by vemneyy** [comment]
same issue

**Comment by SpectreChazer** [comment]
same issue :(

**Comment by toxic-dew** [comment]
same here

**Comment by clovelt** [comment]
Same here!

**Comment by delef** [comment]
same

**Comment by vemneyy** [comment]
fixed by latest spotify update and spicetify reinstall

**Comment by ms-dc** [comment]
> fixed by latest spotify update and spicetify reinstall

I have also fixed by reinstalling both spotify and spicetify
